# Generated by Django 3.2.7 on 2021-11-16 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.CharField(default=0, max_length=255, verbose_name='Баланс')),
                ('price_of_all_indexes', models.CharField(default=0, max_length=255, verbose_name='Цена всех индексов')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Финансовая информация пользователей',
                'verbose_name_plural': 'Финансовая информация пользователей',
            },
        ),
        migrations.CreateModel(
            name='SharingMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_operation', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата операции')),
                ('status', models.CharField(choices=[('payed', 'Оплачено'), ('discline', 'Отказ'), ('processing', 'В процессе')], default='processing', max_length=255, verbose_name='Статус вывода')),
                ('summ', models.CharField(max_length=255, verbose_name='Сумма на вывод')),
                ('way_to_pay', models.CharField(max_length=255, verbose_name='Способо оплаты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сумма на вывод пользователя',
                'verbose_name_plural': 'Сумма на вывод пользоваталей',
            },
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(auto_now_add=True, db_index=True, verbose_name='Дата покупки')),
                ('state', models.CharField(max_length=255, verbose_name='Статус')),
                ('name', models.CharField(max_length=255, verbose_name='Название индекса')),
                ('price', models.CharField(default=0, max_length=255, verbose_name='Цена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Индекс',
                'verbose_name_plural': 'Индексы',
            },
        ),
        migrations.CreateModel(
            name='HistroyOfСonsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summ', models.CharField(default=0, max_length=255, verbose_name='Сумма траты')),
                ('date_of_operation', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата операции')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История расхода пользователя',
                'verbose_name_plural': 'История расхода пользователей',
            },
        ),
        migrations.CreateModel(
            name='HistoryOfTopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summ', models.CharField(default=0, max_length=255, verbose_name='Сумма пополнения')),
                ('date_of_operation', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата операции')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История пополнения пользователя',
                'verbose_name_plural': 'История пополнения пользователей',
            },
        ),
    ]
