# Generated by Django 3.2.6 on 2021-09-14 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_finance',
            new_name='UserFinance',
        ),
        migrations.CreateModel(
            name='HistroyOfСonsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summ', models.CharField(default=0, max_length=255, verbose_name='Сумма траты')),
                ('time_of_spend', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время расхода')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryOfTopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summ', models.CharField(default=0, max_length=255, verbose_name='Сумма пополнения')),
                ('time_of_payment', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время пополнения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
