# Generated by Django 3.2.6 on 2021-09-24 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20210923_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historyoftopup',
            old_name='time_of_payment',
            new_name='date_of_operation',
        ),
        migrations.RenameField(
            model_name='histroyofсonsumption',
            old_name='time_of_spend',
            new_name='date_of_operation',
        ),
    ]
