# Generated by Django 3.2.6 on 2021-09-24 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0004_auto_20210924_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyoftopup',
            name='date_of_operation',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата операции'),
        ),
        migrations.AlterField(
            model_name='histroyofсonsumption',
            name='date_of_operation',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата операции'),
        ),
        migrations.CreateModel(
            name='SharingMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_operation', models.DateField(auto_now_add=True, db_index=True, verbose_name='Дата операции')),
                ('status', models.CharField(max_length=255, verbose_name='Статус вывода')),
                ('summ', models.CharField(max_length=255, verbose_name='Сумма на вывод')),
                ('way_to_pay', models.CharField(max_length=255, verbose_name='Способо оплаты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
