# Generated by Django 3.2.6 on 2021-09-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20210924_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharingmoney',
            options={'verbose_name': 'Сумма на вывод пользователя', 'verbose_name_plural': 'Сумма на вывод пользоваталей'},
        ),
        migrations.AlterField(
            model_name='sharingmoney',
            name='date_of_operation',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата операции'),
        ),
        migrations.AlterField(
            model_name='sharingmoney',
            name='status',
            field=models.CharField(choices=[('payed', 'PAYED'), ('discline', 'DISCLINE'), ('processing', 'PROCESSING')], default='processing', max_length=255, verbose_name='Статус вывода'),
        ),
    ]
