# Generated by Django 3.2.7 on 2021-09-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20210924_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharingmoney',
            name='status',
            field=models.CharField(choices=[('payed', 'Оплачено'), ('discline', 'Отказ'), ('processing', 'В процессе')], default='processing', max_length=255, verbose_name='Статус вывода'),
        ),
    ]
