# Generated by Django 3.2.7 on 2021-11-16 10:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_blacklist_blocked_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='blocked_user',
        ),
        migrations.AddField(
            model_name='blacklist',
            name='blocked_users',
            field=models.ManyToManyField(null=True, related_name='user_who_blocked_you', to=settings.AUTH_USER_MODEL),
        ),
    ]
