# Generated by Django 3.2.7 on 2021-11-16 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211116_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='blocked_users',
            field=models.ManyToManyField(related_name='user_who_blocked_you', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='adress',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Прописка'),
        ),
        migrations.AlterField(
            model_name='user',
            name='adress_of_living',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Адресс фактического проживания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='citizenship',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='city_of_born',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Город рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, default='1970-03-19', null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='user',
            name='inn',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='user',
            name='number_of_bank_cart',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Номер банковской карты'),
        ),
        migrations.AlterField(
            model_name='user',
            name='office',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Офис'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pasport_date_of_gave',
            field=models.DateField(blank=True, default='1970-03-19', null=True, verbose_name='Паспорт дата выдачи'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pasport_number',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Паспорт номер'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pasport_serial',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Паспорт серия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pasport_who_gave',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='user',
            name='snils',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='СНИЛС'),
        ),
        migrations.AlterField(
            model_name='user',
            name='town',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Город'),
        ),
    ]
