# Generated by Django 3.2.6 on 2021-09-23 17:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210923_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_activate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
