# Generated by Django 3.2.6 on 2021-09-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_user_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_activate',
            field=models.DateField(verbose_name='Дата активации'),
        ),
    ]
