# Generated by Django 3.2.6 on 2022-01-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='фейсбук'),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='инстаграм'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='телеграм'),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='твиттер'),
        ),
        migrations.AddField(
            model_name='user',
            name='vk',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='вк'),
        ),
        migrations.AddField(
            model_name='user',
            name='youtube',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='ютуб'),
        ),
        migrations.AlterField(
            model_name='user',
            name='citizenship',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Страна рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pasport_who_gave',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Кто выдал паспорт'),
        ),
    ]
