# Generated by Django 3.2.7 on 2021-09-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_date_of_activate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_choice',
            field=models.CharField(choices=[('0', 'Отсутствует'), ('2', 'СМС'), ('3', 'email'), ('4', 'СМС+email')], default='0', max_length=255),
        ),
    ]
