# Generated by Django 3.2.7 on 2021-09-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210928_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_activate',
            field=models.DateField(blank=True, default=None, verbose_name='Дата активации'),
        ),
    ]
