# Generated by Django 3.2.7 on 2021-09-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_user_date_of_activate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_activate',
            field=models.DateField(blank=True, verbose_name='Дата активации'),
        ),
    ]
