# Generated by Django 3.2.7 on 2021-09-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_user_date_of_activate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_for_email',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Код для почты'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_choice',
            field=models.CharField(choices=[('absent', 'Отсутствует'), ('SMS', 'СМС'), ('email', 'email'), ('SMS_email', 'СМС + email')], default='0', max_length=255),
        ),
    ]
