# Generated by Django 3.2.7 on 2022-01-21 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineusers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnlineUserActivity',
        ),
    ]
