# Generated by Django 3.2.7 on 2021-10-07 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('descripton', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('pic', models.ImageField(upload_to='', verbose_name='Аватар')),
                ('users', models.ManyToManyField(related_name='Участники', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Конкурсы',
                'verbose_name_plural': 'Конкурсы',
            },
        ),
    ]
