# Generated by Django 3.2.7 on 2021-11-16 09:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_of_answer', models.CharField(max_length=255)),
                ('users', models.ManyToManyField(blank=True, related_name='Answers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('date_of_expired', models.DateTimeField()),
                ('answers', models.ManyToManyField(blank=True, to='contest.Answers', verbose_name='Ответы')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Проголосовавшие')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('price', models.CharField(max_length=255, verbose_name='Стоимость на вход')),
                ('pic', models.ImageField(upload_to='', verbose_name='Аватар')),
                ('expired_date', models.DateTimeField(verbose_name='Дата окончания конкурса')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('end', 'Закончился')], default='active', max_length=255)),
                ('users', models.ManyToManyField(blank=True, related_name='Участники', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Победитель')),
            ],
            options={
                'verbose_name': 'Конкурс',
                'verbose_name_plural': 'Конкурсы',
                'ordering': ['-expired_date'],
            },
        ),
    ]
