# Generated by Django 3.2.7 on 2021-10-11 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='descripton',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='contest',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='Участники', to=settings.AUTH_USER_MODEL),
        ),
    ]
