# Generated by Django 3.2.7 on 2021-10-11 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0002_auto_20211011_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='Участники', to=settings.AUTH_USER_MODEL),
        ),
    ]
