# Generated by Django 3.2.7 on 2021-10-11 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_alter_contest_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ['-expired_date'], 'verbose_name': 'Конкурсы', 'verbose_name_plural': 'Конкурсы'},
        ),
        migrations.AddField(
            model_name='contest',
            name='expired_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата окончания конкурса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contest',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='price',
            field=models.CharField(max_length=255, verbose_name='Выигрыш'),
        ),
    ]
